name: 'make-snapshot'
description: 'Make snapshot tarballs'
inputs:
  version:
    description: 'Target Version'
    required: false
  shallow-since:
    description: 'git fetch --shallow-since'
    required: true
    default: '2018-12-25 00:00:00'
  fetch-branch:
    description: 'fetch branch'
    required: false
  generate-tar-bz2:
    description: 'Generate .tar.bz2'
    required: false

runs:
  using: "composite"
  steps:
    - name: Install libraries
      run: |
        set -x
        sudo apt-get update -q || :
        sudo apt-get install --no-install-recommends -q -y build-essential git bison autoconf ruby p7zip-full curl
      shell: bash
    - name: Checkout ruby/ruby for tool/make-snapshot
      run: git clone --single-branch --depth=1 https://github.com/ruby/ruby ruby
      shell: bash
    - name: Fetch branches and notes
      run: |
        set -x
        cd ruby
        git fetch --shallow-since='${{ inputs.shallow-since }}'
        [ -n "${{ inputs.fetch-branch }}" ] && git fetch origin '+${{ inputs.fetch-branch }}:${{ inputs.fetch-branch }}'
        git fetch origin '+refs/notes/commits:refs/notes/commits'
        git fetch origin '+refs/notes/log-fix:refs/notes/log-fix'
      shell: bash
    - name: Make snapshot
      run: >-
        ruby ruby/tool/make-snapshot -archname=$archname -srcdir=ruby
        ${{ !inputs.generate-tar-bz2 && '-packages=gzip,xz,zip' }}
        pkg ${{ inputs.version }}
      shell: bash
