name: snapshot-ruby_4_0

on:
  schedule:
    - cron: '30 18 * * *' # Daily at 18:30 UTC
  repository_dispatch:
    types:
      - "make-snapshot"
      - "snapshot-ruby_4_0"
  workflow_dispatch:
    inputs:
      RUBY_PATCH_URL:
        description: Patch URL
        required: false

jobs:
  upload:
    uses: ./.github/workflows/upload-tarball.yml
    with:
      archname: snapshot-ruby_4_0
      version: "4.0"
      fetch-branch: ruby_4_0
    secrets: inherit

  ubuntu:
    needs: upload
    uses: ./.github/workflows/snapshot-ubuntu.yml
    with:
      archname: snapshot-ruby_4_0
      allow-failures: power_assert
      patch-url: ${{ inputs.RUBY_PATCH_URL }}
      remove-gnupg: true
      notify-ruby-sha: true
      branch-label: ruby_4_0
    secrets: inherit

  macos:
    needs: upload
    uses: ./.github/workflows/snapshot-macos.yml
    with:
      archname: snapshot-ruby_4_0
      allow-failures: power_assert
      patch-url: ${{ inputs.RUBY_PATCH_URL }}
    secrets: inherit

  windows:
    needs: upload
    uses: ./.github/workflows/snapshot-windows.yml
    with:
      archname: snapshot-ruby_4_0
      patch-url: ${{ inputs.RUBY_PATCH_URL }}
      mode: modern
    secrets: inherit

  non_development:
    needs: upload
    uses: ./.github/workflows/snapshot-non-development.yml
    secrets: inherit
