name: snapshot-ruby_3_3

on:
  schedule:
    - cron: '30 18 * * *' # Daily at 18:30 UTC
  repository_dispatch:
    types:
      - "make-snapshot"
      - "snapshot-ruby_3_3"
  workflow_dispatch:
    inputs:
      RUBY_PATCH_URL:
        description: Patch URL
        required: false

jobs:
  tarball:
    uses: ./.github/workflows/snapshot-tarball.yml
    with:
      archname: snapshot-ruby_3_3
      version: "3.3"
      fetch-branch: ruby_3_3
    secrets: inherit

  ubuntu:
    needs: tarball
    uses: ./.github/workflows/snapshot-ubuntu.yml
    with:
      archname: snapshot-ruby_3_3
      patch-url: ${{ inputs.RUBY_PATCH_URL }}
      apt-mode: ruby-and-git
      setup-host-ruby: false
      fixed-dirs-extra: false
      ruby-bin: ruby
    secrets: inherit

  macos:
    needs: tarball
    uses: ./.github/workflows/snapshot-macos.yml
    with:
      archname: snapshot-ruby_3_3
      patch-url: ${{ inputs.RUBY_PATCH_URL }}
      rebuild-homebrew-ruby: true
    secrets: inherit

  windows:
    needs: tarball
    uses: ./.github/workflows/snapshot-windows.yml
    with:
      archname: snapshot-ruby_3_3
      patch-url: ${{ inputs.RUBY_PATCH_URL }}
      mode: legacy
    secrets: inherit

  non_development:
    needs: tarball
    uses: ./.github/workflows/snapshot-non-development.yml
    secrets: inherit
