name: snapshot-master

on:
  schedule:
    - cron: '30 18 * * *' # Daily at 18:30 UTC
  repository_dispatch:
    types:
      - "make-snapshot"
      - "snapshot-master"
  workflow_dispatch:
    inputs:
      RUBY_PATCH_URL:
        description: Patch URL
        required: false

jobs:
  tarball:
    uses: ./.github/workflows/snapshot-tarball.yml
    with:
      archname: snapshot-master
    secrets: inherit

  ubuntu:
    needs: tarball
    uses: ./.github/workflows/snapshot-ubuntu.yml
    with:
      archname: snapshot-master
      allow-failures: power_assert
      patch-url: ${{ inputs.RUBY_PATCH_URL }}
      remove-gnupg: true
      notify-ruby-sha: true
      branch-label: master
    secrets: inherit

  macos:
    needs: tarball
    uses: ./.github/workflows/snapshot-macos.yml
    with:
      archname: snapshot-master
      allow-failures: power_assert
      patch-url: ${{ inputs.RUBY_PATCH_URL }}
    secrets: inherit

  windows:
    needs: tarball
    uses: ./.github/workflows/snapshot-windows-modern.yml
    with:
      archname: snapshot-master
      patch-url: ${{ inputs.RUBY_PATCH_URL }}
    secrets: inherit

  non_development:
    needs: tarball
    uses: ./.github/workflows/snapshot-non-development.yml
    secrets: inherit
