# frozen_string_literal: true

ruby ENV['CUSTOM_RUBY_VERSION'] || '~> 2.7.2'

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "rake"
gem "aws-sdk-s3"
